- name:  Set up Jenkins
  hosts: all
  gather_facts: true
  sudo: yes
  tasks:
  - name: add key
    apt_key: url=http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key

  - name: create sources list
    shell: echo deb http://pkg.jenkins-ci.org/debian binary/ > /etc/apt/sources.list.d/jenkins.lists

  - name: apt-get update 
    apt: update_cache=yes

  - name: install jenkins
    apt: pkg=jenkins state=latest
    notify: start jenkins

  handlers:
  - name: start jenkins
    service: name=jenkins state=started